devzes/pnotes

functions/views/desktop.ejs
functions/views/login.ejs

fix issue of tab in textarea

---

new_site/public/css/laptop-style.css

kya tha ye priyam? xD
Fixes #32

issue of removing underline from anchor tag closed

---

new_site/public/org/index.html

#35 
Asks for a name and checks if an org already exists, if yes asks for a password and checks again.
If not then creates the org and prompts to set a password.

organization notes initiated

---

new_site/functions/views/laptop.ejs
new_site/public/js/laptop-end.js
new_site/public/js/share.js
new_site/public/js/theme.js
new_site/public/share

Note Sharing Page created!
One of the best needed feature, however link creation is still to be done

Note sharing page created

---

new_site/public/css/laptop-style.css

changed top navigation bar

---

new_site/public/css/laptop-style.css

changed search box text colour

---

new_site/functions/views/laptop.ejs
new_site/public/css/laptop-style.css
new_site/public/js/laptop-end.js

check out @Signior-X Fixes #46

made sidebar resizeable using spilt

---

new_site/public/js/laptop-end.js

cleaning of code 
remove useless variable

Claning useless variables

---

package-lock.json
public/js/laptop-end.js

Fixed delete button bug

---

public/org

@Signior-X  pls verify.
Fixes #71

Issue#71 Logo now visible in tab(in org page)

---

public/js/laptop-end.js
public/org

Issue#72 Autosave notes in 3s. 

---

functions/routes/route.js
public/js/share.js

Refractored code,changed variable names (#75)

---

functions/package-lock.json

`npm update` to fix the dependencies.

Update NPM dependencies

---

functions/views/laptop.ejs
public/js/finit.js

Updates the firebase links so that the project can be used from anywhere.

Updated firebase links and added firebase init js

---

public/css/laptop-style.css

Fix the height problem with flex for editors and previews.

---

public/share

Changed the specified links to given format in file public/share

---

public/js/laptop-end.js

3 seconds is a too long time to auto save.
Update it with this.

Change timer to 2 seconds

---

README.md
public/index.html

This is the biggest breaking change in pnotes.
This removes the sign in from google feature and
focus is now only on org features.

Shift from nodeJS to static site

---

public/css/laptop-style.css

By this PR fixes the issue of dark mode place holder #84. changes added to CSS file.

update darkmode search placeholder text visibility

---

public/css/laptop-style.css

Very important fix and solves the error.
Thanks @Ritam727

Fixed scroll errors by removing custom heights and using flex

---

public/css/laptop-style.css

Please suggest any changes required.

Fixed the highlighting of the selected text in edit mode #83
